apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: ping-server
build:
  artifacts:
    - image: your-dockerhub-username/your-image-name
      context: .
      jib:
        project: com.example:ping-server
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: deployment
    resourceName: ping-server
    port: 8080
    localPort: 8080
